### ISSUE TITLE
ruckus-cli2: not found

### ISSUE THREAD

**Issue by freelingchang** [ms264556/Hackery#1]
ruckus> enable
ruckus# debug
You have all rights in this mode.
ruckus(debug)# script
ruckus(script)# exec ../../../bin/sh

Ruckus Wireless ZoneDirector -- Command Line Interface
Enter 'help' for a list of built-in commands.

ruckus$ /writable/etc/scripts/../../../bin/sh: ruckus-cli2: not found

R500 US
R500_200.6.10.1.312.bl7
thanks

**Comment by ms264556** [comment]
Sorry, There was a typo.

The correct command is `ruckus_cli2` (with an underscore rather than a hyphen).

I've update the page with the correct command now.
