### ISSUE TITLE
Ruckus certificate script not working

### ISSUE THREAD

**Issue by Churator** [ms264556/Hackery#12]
Thanks for the script
however, it seems to not work with Unleashed 200.14 atleast.
Tried to tweak it a bit (Effective URL say 404, so used admin/login.jsp for CSRF, but the tr -d cut it all, so removed it)
still, can't make it work :q/

**Comment by ms264556** [comment]
What are you running it from? pfSense? or a Linux distro?

**Comment by Churator** [comment]
OPNsense actually, BSD.

**Comment by ms264556** [comment]
And you've setup split DNS for the FQDN you're using for Unleashed? I.e. you can ping the FQDN and it returns your unleashed master IP?

**Comment by ms264556** [comment]
OK. I just ran the script from the commandline of a pfSense box (BSD) to an AP running Unleashed 200.14.6.1.199. It worked OK.

You need to make sure that you've setup split dns correctly - if your Unleashed master has IP `192.168.1.99` and you want your AP's web UI to live at `https://unleashed.churator.net` then your OPNsense box should already resolve `192.168.1.99` when you `ping unleashed.churator.net`.

And you need to make sure you've replaced `myruckususername` and `myruckuspassword` with your actual Unleashed admin user and password, that the paths to the fullchain and key files are correct, and the fullchain is for either your AP's fqdn or a wildcard at the same level as your AP's name.

Then you're calling the script with the fullchain, key & fqdn as args, e.g. (for a wildcard cert) `/path/to/export_zd_cert.sh /path/to/churator.net.fullchain /path/to/churator.net.key unleashed.churator.net`

**Comment by ms264556** [comment]
Hi @Churator. Do let me know if my comments helped you to get this working, so I can close the issue

**Comment by Churator** [comment]
Hi
I can't make it work from OPNsense CLI, but I'll keep trying since you verified its working.
