### ISSUE TITLE
Only to say thanks for the Ruckus region unlock

### ISSUE THREAD

**Issue by mikegleasonjr** [ms264556/Hackery#4]
So thanks and happy holidays :P

**Comment by ms264556** [comment]
You're most welcome! Hope it saved you some money and made your internet better!

**Comment by mikegleasonjr** [comment]
> You're most welcome! Hope it saved you some money and made your internet better!

Yes I am living abroad and came to visit my family in Canada, couldn't find any ww00 at a reasonable price!

Will have good wifi when I'll come back 🫶
