### ISSUE TITLE
How did you figure out that 0x0f is the DisplayPort for ddcutil for controlling inputs of a Dell monitor in Linux?

### ISSUE THREAD

**Issue by imthenachoman** [ms264556/Hackery#6]
I am looking at https://github.com/ms264556/Hackery/blob/master/pages/InputSwitchHotkey.md.

First, thanks so much for sharing this information.

I am looking at the line `ddcutil setvcp 60 0x0f`.

How did you figure out the `60 0x0f` part?

**Comment by ms264556** [comment]
Sorry, this is a very bare-bones description of the steps, and maybe there's a better description elsewhere now.

You can look your monitor up here: [https://github.com/ddccontrol/ddccontrol-db/tree/master/db/monitor](https://github.com/ddccontrol/ddccontrol-db/tree/master/db/monitor) 

Then look at the inputsource element.

**Comment by imthenachoman** [comment]
Thanks. I was able to figure it out. Works well. Figuring this out was one of the main things keeping me on Windows 10.

**Comment by ms264556** [comment]
Added a short explanation and link.
