### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by kazihaha** [ms264556/Hackery#7]
Hi, I paste it to python 3.11 and get this
`function ruckus_getadmin {
  File "<stdin>", line 1
    function ruckus_getadmin {
             ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
>>> RUCKUS_BAK="$1" python3 - <<END
  File "<stdin>", line 1
    RUCKUS_BAK="$1" python3 - <<END
                    ^^^^^^^
SyntaxError: invalid syntax
>>> import io
>>> import os
>>> import struct`
Please, how can I fix?

**Comment by ms264556** [comment]
It's for pasting into a bash shell. It's a bash shell function, rather than
a python function. If it doesn't work when pasted into bash then let me
know your distro and I can test.

**Comment by kazihaha** [comment]
Oh thanks for your clearify, I trying to paster to wsl on windows, it worked :D
